{% set version = "0.4.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lemon
  version: {{ version|replace("-", "_") }}

source:
  fn: lemon_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/lemon_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/lemon/lemon_{{ version }}.tar.gz
  sha256: a56d5eeab805893dbfe00a3f7eefc93eca40ce305022db358f49267022c73055

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-gridextra
    - r-gtable
    - r-knitr >=1.12
    - r-lattice

  run:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-gridextra
    - r-gtable
    - r-knitr >=1.12
    - r-lattice

test:
  commands:
    - $R -e "library('lemon')"  # [not win]
    - "\"%R%\" -e \"library('lemon')\""  # [win]

about:
  home: https://github.com/stefanedwards/lemon
  license: GPL-3
  summary: Functions for working with legends and axis lines of 'ggplot2', facets that repeat axis lines on all panels, and some 'knitr' extensions.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
