travis:
  secure:
    BINSTAR_TOKEN: DbVuPSxqI9A+9OxkvbyXz1sag+/NMwIxk9wgtU/YaDuurQAY8ed2PuFuxs75uGyJxXNXm22DnbBf+xh6OzyLKx7oqZ2xL/93qHKyRLVm3ek8GsB7HRb42S/I2fzEcJ+viEJiFYAsNfu45PPcuvPY0yfm9qWiqdhDG+YDaXjSx7QRfzXuD3nt+FIXyEvSEJJTyjoFiSwriGM8IhsDhYTqeUF4mmAwNWHdzcTGi3CUPtOqCdbKrOfo35qfVYZUuVs9vyAaO9OFHw+BGOMr+kuB3pCns/aS1CcNGjZTy6ISXV/ol1i1o8WL+dzUIp40Jv210R9nr3sYyNaVTpon8wIudVUGvBnMZDJadm5PmVi4/6RTzhjdnrSOQMW0JOPA1KvaLJWGO0wi3xACSbGKkS7QRJyxF6BClRd7TU6xE7oIYoFAWYhX/fyo/LguGy3w/Ob0K3XPU2BFrUNXd9a/AuYrNaqtsRTc1SaYwLC34tmrnkpCtDaJaFzkb3KgHputHdGq/9G6di4khWnEBwygclh6sXlilNW1ZBX9fhe19CwKzfXMWjzij3pWviHqXa6tWp2yHcpCMbm398dAh3Itub60V4A234218aEGWNWov0V+O92PKlB5ryHb0PvOxfiZd852RmHlvW3yH6y/ZQmROALdwwGPGB3c0InanmuFxhekVdo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
