travis:
  secure:
    BINSTAR_TOKEN: zbO4LmWQhI38aLx+AhpOBgXnPX5Y1Ca+i14Jf9itnfyMuLxv5kZPlzcaQniFY+UC9kHofgk/frNqdnnPmtHjCzt8F1P7axd2FZXLGkuLn2LEWofOESy+aEpfHT/x2t+Dpf5xczeTJTL68ZchZEDpeggfUByRoENXGOvA3jl12mSEBSDFFql4SnzsiCDliUJbk+pQsgEmYwMNUeRUUPhZSpsvhOKKs6NBuxR0eEPRjw0IO0LA3AajVH51aH760yKQqAxfdh9eK8T1MoQ5q+jTrbdy9SmL2DGxzS30491t+FfEWNMUW+aBxPW45Io7PYbcJVZ3sZqJq2p5ZB66LSuI00HJjD6MgmpbVJN0Wz0fltfPXaV4hacU3uNXV4qzgeSMKF+azmMJPIY8O8dnq4sTa1VeUGYlukN5EyGBDSNncS+cCErqFpOtYP98nZNp2nUwky2HymftP5+m4PrxQliLvXhthq+6nIvYLiTDu9jlndn57mQlSag54mLCzy3VqOml8JMKhK/whi9U/bmdeoq9hSDJ6VY60IXHgh54nXWyXD3plzkD4aBkKYGErl2yw/ZJCaR22bQZwiLx8v1PqiNqnmNK6CBP11iSLD06hfiMekIIlXWXKCK/uFNpqyxLWZTXMUNZtFP3fiMViMG6Sf07CeSXCNkDKCGPxOTYFJzhwb0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
